[package]
name = "minidump-analyzer-test"
description = "Tests minidump-analyzer using crates which we won't vendor."
version = "0.1.0"
authors = ["Alex Franchuk <alex.franchuk@gmail.com>"]
license = "MPL-2.0"
edition = "2018"

[dev-dependencies]
crash-handler = "0.6"
minidumper = "0.8"
json = "0.12.4"
sadness-generator = "0.5.0"
tempfile = "3.3.0"

[workspace]
