name: Build Wunderfox, fork of Firefox.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Set environment variables for the build
      CC: clang
      CXX: clang++
      MOZCONFIG: ${{ github.workspace }}/mozconfig

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1 # Shallow clone to save disk space

      - name: Show disk before cleanup
        run: df -h

      # 1) Expand usable disk on the runner and add swap
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024            # keep 1 GB free for system
          swap-size-mb: 4096               # add 4 GB swap to reduce OOM risk
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      # 2) Prune remaining large toolchains/caches
      - name: Free additional disk space
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          tool-cache: true
          swap-storage: true

      - name: Extra manual pruning (belt & suspenders)
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          sudo docker system prune -af --volumes || true
          sudo apt-get clean || true
          sudo rm -rf /var/lib/apt/lists/* || true

      - name: Show disk after cleanup
        run: df -h

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf2.13 \
            build-essential \
            clang \
            cmake \
            curl \
            git \
            libasound2-dev \
            libcurl4-openssl-dev \
            libgtk-3-dev \
            libpulse-dev \
            libssl-dev \
            libx11-xcb-dev \
            libxcb-glx0-dev \
            libxcb-shm0-dev \
            libxcb1-dev \
            libxt-dev \
            nodejs \
            python3 \
            python3-pip \
            unzip \
            zip
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Set Up Python Environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install virtualenv
        env:
          PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache # Use temp directory for pip cache

      - name: Create Build Directory
        run: mkdir objdir

      - name: Configure Build
        run: |
          cd objdir
          ../mach configure
        env:
          MOZBUILD_STATE_PATH: ${{ runner.temp }}/mozbuild # Store state in temporary directory

      - name: Build Firefox
        run: |
          cd objdir
          ../mach build
        env:
          MOZBUILD_STATE_PATH: ${{ runner.temp }}/mozbuild

      - name: Run Tests
        run: |
          cd objdir
          ../mach test
        env:
          MOZBUILD_STATE_PATH: ${{ runner.temp }}/mozbuild

      - name: Clean Up Build Directory
        run: |
          rm -rf objdir/.deps objdir/.mozbuild

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firefox-build
          path: objdir/dist/
          retention-days: 7 # Reduce storage time
